### ISSUE TITLE
Tail new log option is missing after opening one log file

### ISSUE THREAD

**Issue by yosigolan** [otros-systems/otroslogviewer#480]
Hey.
Since version 1.4.6 the option in the file menu for tail log is missing after opening a file in tail mode.
this is how the file menu looks like in version 1.4.7:
![image](https://user-images.githubusercontent.com/18391088/36470046-24ffea12-16f2-11e8-9fa0-80c498afb559.png)

this is how the file menu looks like in version 1.4.5:
![image](https://user-images.githubusercontent.com/18391088/36470103-626f2b24-16f2-11e8-8f8a-01f3f13926e2.png)

**Comment by otrebski** [comment]
I have decided to reorganise file loading. With a large numbers of log parser (patterns to parse):
 * It can be confusing to select matching log pattern
 * Menu get bigger and bigger, the same for welcome screen
 * `Open` and `Tail` can be confusing for user. Especially if tail is starting from begging of the file (instead of almost end)
Open log files will allow you to open (in tail mode) selected log files and choose log pattern/parser to use. Additionally you can save combination of log files to open.

**Comment by otrebski** [comment]
@yosigolan If you have any suggestion about UX and usability, I will be happy to hear it.

**Comment by yosigolan** [comment]
Hey @otrebski . thanks for you answer but i cant figure out how to do it.... can you explain how to open a file in tail mode using the open log file option?
