### ISSUE TITLE
Log view with Socket Listener has sizeable lag

### ISSUE THREAD

**Issue by asoltesz** [otros-systems/otroslogviewer#577]
When using a log view with the Socket Listener, sometimes I have as long as 4-5 seconds between the time the log is sent from the application (logback) and displays in OTROS.

The socket type is "Logback - socket", port is 50505.

I cross-checked it with LogMX and that displays the messages near instantly, so the delay is not on the application/logback side.

NOTE: I don't seem to find any setting for the delay on the log table/view or in the Preferences, so it is probably hard-coded.

OS: Linux Mint 19.3 x64
OTROS: 1.4.13
JRE: openjdk version "11.0.8"
Memory: -Xmx1024m (unchanged)

-----
BTW: Thanks for all the hard work on OTROS, it has been a great help for me over the years.

**Comment by otrebski** [comment]
Hi.
OtrosLogViewer is parsing logs and adding them in batches to UI. It uses https://github.com/otros-systems/otroslogviewer/blob/master/OtrosLogViewer-app/src/main/java/pl/otros/logview/BufferingLogDataCollectorProxy.java
As you can see here: https://github.com/otros-systems/otroslogviewer/blob/master/OtrosLogViewer-app/src/main/java/pl/otros/logview/gui/actions/StartSocketListener.java#L72 logs are added to UI every 4000ms. It is not configurable.
As a workaround you can change this value to 100ms and build application with `./gradlew dist`

Additionally if you are parsing input from socket OLV can't tell if buffered input is complete log line or more data will be send. Due to this last log event is not parsed and send to UI.

**Comment by asoltesz** [comment]
@otrebski Many thanks
