### ISSUE TITLE
Parse clipboard - java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by DavidAccola** [otros-systems/otroslogviewer#620]
How large of a clipboard copy/paste can OtrosLogViewer reasonably be expected to handle?

![parse clipboard](https://user-images.githubusercontent.com/62493194/164509845-0dbe3b22-0034-4860-98f9-0d6c33a573e7.png)

_java.lang.OutOfMemoryError: Java heap space_

This is pasting what amounts to a 84 mb log file.

**Comment by benlazaro** [comment]
@DavidAccola For now this is tide to the memory allocated for the application. You can change that in the olv batch/shell file. There is an option for setting the max memory allocated to the java process which looks like this:
```
set MEMORY=-Xmx4096m
```
The default value is _-Xmx1024m_ and which that value I was able to reproduce your problem. Once I changed that to the value in the example above, I was able to paste the full log.
I don't think there is anything documented regarding on how much data we should be able to handle in the "Paste clipboard" functionality, but I have 2 possible solutions:

1. We could change the implementation to read the clipboard data in chunks and save it into a temporary file in disk, then we treat it as any other file. The tmp file would need to be deleted on exit. That way can support larger amounts of data pasted from the clipboard without having to modify the memory allocated for the java process.
2. See solution number 1 (I thought I had another one, really)

The pro is that we can handle it the same way than any other log file, though I tried loading the 80Mb file that I created into OLV and it also slapped me with an OutOfMemoryError, which means that we are loading the whole file into memory when we are parsing it, and that's also need to be improved.

So at a minimum I see 1 bug:

- Display a message to inform the end user that the data in the clipboard exceeds the memory limit configured for the application, and explain the steps on how to configure the limit. This way the the application fails gracefully, not showing the exception stack trace.

If we do decide to change the implementation so that we can handle the message in a more performant way, the fix above would not apply anymore since we would not be running out of memory, but there would be other changes in the application that we would need to make:

1. Read the clipboard data in chunks and save it to a tmp log file. (delete file on exit)
2. Read the log file data in chunks as well so that it doesn't require reconfiguring the memory configuration (this may affect other functionality such as search in the log, etc... so we would need to look into that to see if this solution is viable)

**Comment by benlazaro** [comment]
We can also break this into 2 fixes

1. Fix the issue so that the application fails gracefully
2. Create another issue to enhance this functionality, which would be deferred for a bigger milestone.

thoughts anyone?

**Comment by svennissel** [comment]
It is really a bad implementation of Java Clipboard.  I catch the OutOfMemory and display a error message with the hint to change the memory settings. I think this will be work in most cases because if the Clipbord Method will after leave release the memory.

![memory limit reached](https://user-images.githubusercontent.com/40182921/164993816-8b54e757-265f-44ac-b3fc-61cc7813c955.png)

**Comment by benlazaro** [comment]
Just a quick note, the word "to" is repeated in the error message, in case you haven't caught it yet. It should be "too big **to** parse".
